// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBscE0db38D8To2SqiHS7-_hqOgxuHl6IQ',
    appId: '1:177461972695:web:c02feb20102b8f53656a92',
    messagingSenderId: '177461972695',
    projectId: 'chatappmsg-33548',
    authDomain: 'chatappmsg-33548.firebaseapp.com',
    storageBucket: 'chatappmsg-33548.appspot.com',
    measurementId: 'G-Q6GDCEENVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuxY51q4eXEWoLbnbHzW-TlBE8mXfD7fQ',
    appId: '1:177461972695:android:da098838e931e822656a92',
    messagingSenderId: '177461972695',
    projectId: 'chatappmsg-33548',
    storageBucket: 'chatappmsg-33548.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdHJH58Z8SrFbdS-6BMJZzW-hReImWZvc',
    appId: '1:177461972695:ios:bdf2e27f73197c44656a92',
    messagingSenderId: '177461972695',
    projectId: 'chatappmsg-33548',
    storageBucket: 'chatappmsg-33548.appspot.com',
    iosBundleId: 'com.example.chatmessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdHJH58Z8SrFbdS-6BMJZzW-hReImWZvc',
    appId: '1:177461972695:ios:bdf2e27f73197c44656a92',
    messagingSenderId: '177461972695',
    projectId: 'chatappmsg-33548',
    storageBucket: 'chatappmsg-33548.appspot.com',
    iosBundleId: 'com.example.chatmessenger',
  );
}
